const test = require("ava");
const fs = require("fs");
const {
	promisify,
} = require("util");

const assertExpectedLines = require("../helper/assert-expected-lines");

const writeFile = promisify(fs.writeFile);

test("lines", async (t) => {
	const {
		generate,
	} = require("../..");

	const generated = await generate({
		filepath: `${__filename}.h`,
		library: "does-not-matter",
	});

	await writeFile(__filename + ".output.js", generated.serialized);

	t.deepEqual(generated.unmapped, []);

	const expected = `/*
	* This file was generated by @ffi-packager/ffi-generate v
	* https://github.com/node-ffi-packager/node-ffi-generate
	*/`;

	assertExpectedLines(t, expected, generated.serialized);
});
